"""Initial migration

Revision ID: f84ed814b1b8
Revises: 001
Create Date: 2025-12-22 08:33:06.340830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f84ed814b1b8'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('connected_at', sa.DateTime(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('command_logs',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('client_id', sa.String(length=128), nullable=False),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_command_logs_client_id'), 'command_logs', ['client_id'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrollments',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intent_mappings',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('intent_name', sa.String(length=128), nullable=False),
    sa.Column('selector', sa.String(length=255), nullable=True),
    sa.Column('plugin_action', sa.String(length=255), nullable=False),
    sa.Column('payload_template', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intent_mappings_intent_name'), 'intent_mappings', ['intent_name'], unique=False)
    op.create_table('plugin_bindings',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('plugin_name', sa.String(length=128), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plugin_bindings_device_id'), 'plugin_bindings', ['device_id'], unique=False)
    op.create_table('plugin_install_jobs',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('plugin_name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('target_agent', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('logs', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plugin_install_jobs_plugin_name'), 'plugin_install_jobs', ['plugin_name'], unique=False)
    op.create_table('plugin_versions',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('plugin_name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('manifest', sa.JSON(), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('artifact_url', sa.String(length=1024), nullable=True),
    sa.Column('signature', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plugin_versions_plugin_name'), 'plugin_versions', ['plugin_name'], unique=False)
    op.create_table('terminal_audit',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('client_id', sa.String(length=128), nullable=True),
    sa.Column('initiator_type', sa.String(length=32), nullable=True),
    sa.Column('initiator_id', sa.String(length=128), nullable=True),
    sa.Column('record_path', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('stopped_at', sa.DateTime(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_terminal_audit_client_id'), 'terminal_audit', ['client_id'], unique=False)
    op.create_index(op.f('ix_terminal_audit_session_id'), 'terminal_audit', ['session_id'], unique=False)
    op.create_index(op.f('ix_plugins_name'), 'plugins', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plugins_name'), table_name='plugins')
    op.drop_index(op.f('ix_terminal_audit_session_id'), table_name='terminal_audit')
    op.drop_index(op.f('ix_terminal_audit_client_id'), table_name='terminal_audit')
    op.drop_table('terminal_audit')
    op.drop_index(op.f('ix_plugin_versions_plugin_name'), table_name='plugin_versions')
    op.drop_table('plugin_versions')
    op.drop_index(op.f('ix_plugin_install_jobs_plugin_name'), table_name='plugin_install_jobs')
    op.drop_table('plugin_install_jobs')
    op.drop_index(op.f('ix_plugin_bindings_device_id'), table_name='plugin_bindings')
    op.drop_table('plugin_bindings')
    op.drop_index(op.f('ix_intent_mappings_intent_name'), table_name='intent_mappings')
    op.drop_table('intent_mappings')
    op.drop_table('enrollments')
    op.drop_table('devices')
    op.drop_index(op.f('ix_command_logs_client_id'), table_name='command_logs')
    op.drop_table('command_logs')
    op.drop_table('clients')
    # ### end Alembic commands ###

